import os

home = os.environ['HOME']
kudir = home + '/Dropbox/Code/Ku/'
eigendir = home + '/Dropbox/Code/Sfinx/eigen-3.0.1'

env = Environment(CPPPATH = [kudir, eigendir], CCFLAGS = '-Wall --std=c++0x -fPIC -rdynamic')
env.Program('dan', Glob('*.cpp') + [kudir + 'gtest/gtest_main.a'], 
    LIBS = ['pthread', 'dl', 'm']
    )
